def draw_road():
    print(" |     |     |      | |       |     |     |")
    print(" |           |      | |       |           |")
    print(" |     |     |      | |       |     |     |")
    print(" |           |      | |       |           |")
    print(" |     |     |      | |       |     |     |")
    print(" |           |      | |       |           |")
    print(" |  |  |  |  |      | |       |  ^  |  ^  |")
    print(" |  v     v  |      | |       |  |     |  |")
    print(" |     |     |      | |       |     |     |")
    print(" |           |      | |       |           |")
    print(" |     |     |      | |       |     |     |")
    print(" |           |      | |       |           |")
    print(" |     |     |      | |       |     |     |")
    print(" |           |      | |       |           |")
    print(" |     |     |      | |       |     |     |")
    print(" |           |      | |       |           |")
    print(" |  |  |  |  |      | |       |  ^  |  ^  |")
    print(" |  v     v  |      | |       |  |     |  |")
    print(" |     |     |      | |       |     |     |")
    print(" |           |      | |       |           |")
    print(" |     |     |      | |       |     |     |")
  
    return
