def draw_lake():
    print("~~~~~~~~~~~")
    print("~~~~~~~~~~~")
    print("~~~~~~~~~~~")
    print("~~~~~~~~~~~")
    print("~~~~~~~~~~~")
    print("~~~~~~~~~~~")
    print("~~~~~~~~~~~")
    print("~~~Lake~~~~")
    print("~~~~~~~~~~~")
    print("~~~~~~~~~~~")
    print("~~~~~~~~~~~")
    print("~~~~~~~~~~~")
    print("~~~~~~~~~~~")
    print("~~~~~~~~~~~")
    return
